name: ssh debug

on:
  workflow_dispatch:
    
jobs:
  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest

    steps:

    - name: Restart systemd service
      uses: appleboy/ssh-action@v1
      with:
       host: ${{ secrets.VPS_HOST }}
       username: ${{ secrets.VPS_USER }}
       password: ${{ secrets.VPS_PASSWORD }}
       fingerprint: ${{ secrets.VPS_KNOWN_HOST }}
       port: 22
       debug: true
       script: |
        sudo systemctl restart my-website.service